// Copyright 2026 Glassbox Users
// SPDX-License-Identifier: Apache-2.0

package protocolreg

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// ── Session recovery: lock file integrity ────────────────────────────────────

// TestUnixHandlerScript_ContainsExecutablePath verifies that the handler
// script generated by unixHandlerScript embeds the registrar's executable
// path so the OS can recover a session by re-invoking the correct binary.
func TestUnixHandlerScript_ContainsExecutablePath(t *testing.T) {
	r := newTestRegistrar(t)
	script := r.unixHandlerScript()

	if !strings.Contains(script, r.executablePath) {
		t.Errorf("handler script must embed the executable path for session recovery;\nscript:\n%s", script)
	}
}

// TestUnixHandlerScript_ForwardsURI verifies that the handler script passes
// "$1" (the URI) to the binary so the OS-delivered deep link is recoverable.
func TestUnixHandlerScript_ForwardsURI(t *testing.T) {
	r := newTestRegistrar(t)
	script := r.unixHandlerScript()

	if !strings.Contains(script, `"$1"`) {
		t.Errorf("handler script must forward the URI as \"$1\" for session integrity;\nscript:\n%s", script)
	}
}

// TestUnixHandlerScript_IsExecutable verifies that when the wrapper is written
// to disk by registerLinux it has the executable bit set, which is required for
// the OS to invoke it during session recovery.
func TestUnixHandlerScript_IsExecutable(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Unix-only: executable bit test")
	}

	r := newTestRegistrar(t)

	if err := os.MkdirAll(filepath.Dir(r.linuxWrapperPath()), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	if err := os.WriteFile(r.linuxWrapperPath(), []byte(r.unixHandlerScript()), 0o755); err != nil {
		t.Fatalf("write wrapper: %v", err)
	}

	info, err := os.Stat(r.linuxWrapperPath())
	if err != nil {
		t.Fatalf("stat wrapper: %v", err)
	}

	if info.Mode()&0o111 == 0 {
		t.Errorf("handler script must be executable (mode %o)", info.Mode())
	}
}

// TestRegister_Linux_WrapperAndDesktopBothWritten verifies that a full Linux
// registration writes both artefacts needed for session recovery: the desktop
// file (for MIME dispatch) and the wrapper script (for binary invocation).
func TestRegister_Linux_WrapperAndDesktopBothWritten(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("Linux-only test")
	}

	r := newTestRegistrar(t)

	// Register will fail at xdg-mime in CI (no display), but the files must be
	// written before that step.
	_ = r.registerLinux()

	if _, err := os.Stat(r.linuxDesktopPath()); err != nil {
		t.Errorf("desktop file must be written for session recovery: %v", err)
	}
	if _, err := os.Stat(r.linuxWrapperPath()); err != nil {
		t.Errorf("wrapper script must be written for session recovery: %v", err)
	}
}

// TestVerificationReport_ElapsedMs_NonNegative verifies that the ElapsedMs
// field introduced for performance profiling is always non-negative, so
// session-recovery tooling can safely display it.
func TestVerificationReport_ElapsedMs_NonNegative(t *testing.T) {
	r := newTestRegistrar(t)
	report, _ := r.Verify()
	if report.ElapsedMs < 0 {
		t.Errorf("ElapsedMs must be non-negative, got %d", report.ElapsedMs)
	}
}

// TestDiagnose_ExecutablePath_IsPopulated verifies that the DiagnosticReport
// always carries the ExecutablePath field so session-recovery tools know which
// binary to validate or re-register.
func TestDiagnose_ExecutablePath_IsPopulated(t *testing.T) {
	r := newTestRegistrar(t)
	report := r.Diagnose()
	if report.ExecutablePath == "" {
		t.Error("DiagnosticReport.ExecutablePath must be populated for session integrity checks")
	}
	if report.ExecutablePath != r.executablePath {
		t.Errorf("ExecutablePath mismatch: want %q, got %q", r.executablePath, report.ExecutablePath)
	}
}
